# Apache core health via mod_status
[[inputs.apache]]
  urls = ["http://127.0.0.1/server-status?auto"]
  response_timeout = "5s"
  insecure_skip_verify = true

  [inputs.apache.tags]
    role = "apache-core"

[[inputs.x509_cert]]
  name_override = "certificate"
  interval = "1h"
  sources = ["https://www.sorogon.eu:443"]

  [inputs.x509_cert.tags]
    role = "tls"

[[inputs.tail]]
  name_override = "apache_log"
  files = ["/var/log/apache2/vhost_status.log"]
  from_beginning = false
  data_format = "grok"
  grok_patterns = ["%{HOSTNAME:vhost} %{NUMBER:status:int} %{NUMBER:duration:int}"]

  [inputs.tail.tags]
    role = "apache-errors"