[[inputs.apache]]
  insecure_skip_verify = true
  response_timeout     = "5s"
  urls                 = ["http://127.0.0.1/server-status?auto"]

  [inputs.apache.tags]
    bucket = "webserver"
    role   = "apache-core"

[[inputs.x509_cert]]
  interval      = "15m"
  name_override = "certificate"
  sources       = ["https://www.sorogon.eu:443"]

  [inputs.x509_cert.tags]
    bucket = "webserver"
    role   = "tls"

[[inputs.tail]]
  data_format    = "grok"
  files          = ["/var/log/apache2/vhost_status.log"]
  from_beginning = false
  grok_patterns  = ["%{HOSTNAME:vhost:tag} %{NUMBER:status:int} %{NUMBER:duration:int}"]
  name_override  = "apache_log"

  [inputs.tail.tags]
    bucket = "webserver"
    role   = "apache-errors"
