# Apache core health via mod_status
[[inputs.apache]]
  urls = ["http://127.0.0.1/server-status?auto"]
  response_timeout = "5s"
  insecure_skip_verify = true

  [inputs.apache.tags]
    role = "apache-core"

# Public-facing vhost checks
[[inputs.http_response]]
  name_override = "frontend_http"
  interval = "30s"
  response_timeout = "5s"
  method   = "GET"
  follow_redirects = true

  urls = [
    "https://www.sorogon.eu/",
    "https://pictures.sorogon.eu/",
    "https://videos.sorogon.eu/",
    "https://files.sorogon.eu/",
    "https://music.sorogon.eu/",
    "https://admin.sorogon.eu/",
    "https://git.sorogon.eu/",
    "https://cloud.sorogon.eu/",
    "https://budget.sorogon.eu/",
    "https://immich.sorogon.eu/",
    "https://piwigo.sorogon.eu/",
    "https://searx.sorogon.eu/",
    "https://torrent.sorogon.eu/",
    "https://grocy.sorogon.eu/",
    "https://grocy2.sorogon.eu/",
    "https://petzi.sorogon.eu/",
    "https://autobrr.sorogon.eu/",
    "https://nas.sorogon.eu/",
    "https://3d-printer.sorogon.eu/",
    "https://fahrplan.sorogon.eu/",
    "https://swingmusic.sorogon.eu/",
    "https://grafana.sorogon.eu/",
    "https://influxdb.sorogon.eu/",
    "https://router.sorogon.eu/"
  ]

  [inputs.http_response.tags]
    role = "frontend-vhost"

# Reverse-proxy backend checks (internal)
[[inputs.http_response]]
  name_override = "backend_http"
  interval = "30s"
  response_timeout = "5s"

  urls = [
    "http://100.0.0.200:30008/",
    "http://100.0.0.200:9001/",
    "http://100.0.0.200:30041/",
    "http://100.0.0.200:30066/",
    "http://100.0.0.200:30053/",
    "http://100.0.0.200:30024/",
    "http://100.0.0.200:30219/",
    "http://100.0.0.200:39283/",
    "http://100.0.0.194:8081/",
    "http://100.0.0.200:30051/",
    "http://100.0.0.200:80/",
    "http://100.0.0.198:80",
    "http://100.0.0.113:8000",
    "http://100.0.0.1:80"
  ]

  [inputs.http_response.tags]
    role = "backend"

[[inputs.net_response]]
  protocol = "tcp"
  timeout  = "3s"
  address  = "127.0.0.1:9090"

  [inputs.net_response.tags]
    service = "cockpit"

[[inputs.net_response]]
  protocol = "tcp"
  address  = "100.0.0.200:80"

  [inputs.net_response.tags]
    service = "nas"

[[inputs.net_response]]
  protocol = "tcp"
  address  = "100.0.0.198:80"

  [inputs.net_response.tags]
    service = "3d-printer"

[[inputs.x509_cert]]
  name_override = "certificate"
  interval = "1h"
  sources = ["https://www.sorogon.eu:443"]

  [inputs.x509_cert.tags]
    role = "tls"

[[inputs.tail]]
  name_override = "apache_log"
  files = ["/var/log/apache2/vhost_status.log"]
  from_beginning = false
  data_format = "grok"
  grok_patterns = ["%{HOSTNAME:vhost} %{INT:status} %{INT:duration}"]

  [inputs.tail.tags]
    role = "apache-errors"