[build-system]
    build-backend = "setuptools.build_meta"
    requires      = ["setuptools>=61", "wheel"]

[project]
    description     = "Grafana Monitoring"
    name            = "grafana-monitoring"
    readme          = "README.md"
    requires-python = ">=3.12"
    version         = "1.0.0"

    license = "AGPL-3.0-or-later"

    authors = [{ name = "Flo Greistorfer" }]

    dependencies = ["Requests~=2.33.1", "apacheconfig~=0.3.2", "proxybroker2 @ git+https://github.com/bluet/proxybroker2.git@v2.0.0b1", "qbittorrent-api==2024.12.71"]

    [project.optional-dependencies]
        dev = ["ruff"]

[tool.setuptools]
    packages = []

[tool.ruff]
    line-length    = 180
    target-version = "py312"

    [tool.ruff.lint]
        ignore = ["E501"]
        select = ["B", "E", "F", "I", "UP"]

    [tool.ruff.format]
        indent-style = "space"
        quote-style  = "double"
