[[inputs.exec]]
  commands    = ["/etc/telegraf/telegraf.d/running_screens.py pi server fahrplan iSponsorBlockTV"]
  data_format = "json_v2"
  interval    = "1m"
  timeout     = "60s"

  [[inputs.exec.json_v2]]
    measurement_name_path = "measurement"

    [[inputs.exec.json_v2.object]]
      path = "data"
      tags = ["screen"]

  [inputs.exec.tags]
    bucket = "webserver"
