[[inputs.exec]]
  interval = "1m"
  commands = ["/etc/telegraf/telegraf.d/running_screens.py pi server fahrplan iSponsorBlockTV"]
  timeout = "60s"
  data_format = "json_v2"

  [[inputs.exec.json_v2]]
    measurement_name_path = "measurement"

    [[inputs.exec.json_v2.object]]
      path = "data"
      tags = ["screen"]
