[[inputs.exec]]
    collection_offset = "30m"
    commands          = [["/etc/telegraf/telegraf.d/solar_radiation.py"]]
    data_format       = "influx"
    interval          = "1h"
    timeout           = "60s"

    [inputs.exec.tags]
        bucket = "weather"
