[[inputs.tail]]
  data_format = "json_v2"
  files = ["/home/pi/StaticGalleryBuilder/logs/latest.jsonl"]

  [[inputs.tail.json_v2]]
    measurement_name = "staticgallerybuilder"
    timestamp_format = "2006-01-02T15:04:05Z07:00"
    timestamp_path = "timestamp"

    [[inputs.tail.json_v2.tag]]
      path = "module"

    [[inputs.tail.json_v2.tag]]
      path = "funcName"

    [[inputs.tail.json_v2.tag]]
      path = "filename"

    [[inputs.tail.json_v2.tag]]
      path = "logger"

    [[inputs.tail.json_v2.tag]]
      path = "level"

    [[inputs.tail.json_v2.field]]
      path = "message"
      type = "string"

    [[inputs.tail.json_v2.field]]
      path = "created"
      type = "float"

    [[inputs.tail.json_v2.field]]
      path = "levelno"
      type = "int"

    [[inputs.tail.json_v2.field]]
      path = "lineno"
      type = "int"

    [[inputs.tail.json_v2.field]]
      path = "msecs"
      type = "int"

    [[inputs.tail.json_v2.field]]
      path = "process"
      type = "int"

    [[inputs.tail.json_v2.field]]
      path = "processName"
      type = "string"

    [[inputs.tail.json_v2.field]]
      path = "relativeCreated"
      type = "float"

    [[inputs.tail.json_v2.field]]
      path = "thread"
      type = "int"

    [[inputs.tail.json_v2.field]]
      path = "threadName"
      type = "string"

    [[inputs.tail.json_v2.field]]
      optional = true
      path = "taskName"
      type = "string"

    [[inputs.tail.json_v2.field]]
      optional = true
      path = "version"
      type = "string"

[[processors.enum]]
  namepass = ["staticgallerybuilder"]

  [[processors.enum.mapping]]
    default = 0
    dest = "level_code"
    tag = "level"

    [processors.enum.mapping.value_mappings]
      CRITICAL = 50
      DEBUG = 10
      ERROR = 40
      INFO = 20
      WARNING = 30

[[processors.override]]
  namepass = ["staticgallerybuilder"]

  [processors.override.tags]
    bucket = "webserver"
