[global_tags]

[agent]
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  interval = "10s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  round_interval = true

[[outputs.influxdb_v2]]
  bucket = "devices"
  bucket_tag = "bucket"
  exclude_bucket_tag = true
  organization = "sorogon"
  token = "token"
  urls = ["http://100.0.0.200:30115", "https://influxdb.sorogon.eu"]

[[inputs.cpu]]
  collect_cpu_time = false
  core_tags = false
  percpu = true
  report_active = false
  totalcpu = true

[[inputs.disk]]
  ignore_fs = ["aufs", "devfs", "devtmpfs", "fuse.snapfuse", "iso9660", "overlay", "rootfs", "squashfs", "tmpfs"]

[[inputs.diskio]]
  device_tags = ["DEVNAME", "DEVTYPE", "ID_FS_TYPE", "ID_MODEL", "ID_SERIAL", "TAGS"]
  skip_serial_number = false

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.net]]
  ignore_protocol_stats = true
  [inputs.net.tags]
    bucket = "network"

[[inputs.nstat]]
  [inputs.nstat.tags]
    bucket = "network"

[[inputs.netstat]]
  [inputs.netstat.tags]
    bucket = "network"

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.systemd_units]]
  details = true
