[[inputs.http]]
    collection_jitter = "2m"
    data_format       = "json"
    interval          = "15m"
    name_override     = "weather"
    tag_keys          = ["elevation", "latitude", "longitude", "utc_offset_seconds"]
    tagexclude        = ["url"]
    urls              = ["https://api.open-meteo.com/v1/forecast?latitude=47.016278&longitude=15.437286&current=temperature_2m,relative_humidity_2m,precipitation,weather_code,cloud_cover,surface_pressure,rain,showers,snowfall&timezone=Europe%2FBerlin"]


    [inputs.http.tags]
        bucket = "weather"
